const deliveryConstants = {
    EDIT_DELIVERY: "EDIT_DELIVERY",
    DELETE_DELIVERY: "DELETE_DELIVERY",
    CURRENT_DELIVERY: "CURRENT_DELIVERY",
    EARLIER_DELIVERIES: "EARLIER_DELIVERIES",
    LATER_DELIVERIES: "LATER_DELIVERIES",
}

export default deliveryConstants;
