const deliveryAddressConstants = {
    GET_ADDRESSES: "GET_ADDRESSES",
    EDIT_ADDRESS: "EDIT_ADDRESS",
    DELETE_ADDRESS: "DELETE_ADDRESS",
    ADD_ADDRESS: "ADD_ADDRESS",
    INCREASE_DELIVERY: "INCREASE_DELIVERY",
    DECREASE_DELIVERY: "DECREASE_DELIVERY",
}

export default deliveryAddressConstants
